### ISSUE TITLE
How to mock HTTP response of Zip file - Getting java.io.EOFException

### ISSUE THREAD

**Issue by abhikt48** [PawelAdamski/HttpClientMock#42]
Do we have any sample for mocking HTTP response of zip file?

I tried to mock response of zip but I am getting `java.io.EOFException`, looks like stream already consumed. I might be doing something wrong. Can you please suggest me any clue for this issue?

**Sample Code** 
```
Action action = new Action() {
	@Override
	public HttpResponse getResponse(Request request) throws IOException {
		BasicHttpResponse response = new BasicHttpResponse(new ProtocolVersion("http", 1, 1), status, statusMessage);
		FileEntity entity = new FileEntity(new File("C:/sample-response.zip"));
		response.setEntity(entity);
		return response;
	}
};

HttpClientMock httpClientMock = new HttpClientMock();
Unirest.config().httpClient(ApacheClient.builder(httpClientMock));

httpClientMock.onGet("http://xxx.com").doAction(action);

// Rest Request Initiated

// Used code to download

HttpGet httpGet = new HttpGet(downloadLocation);
httpGet.addHeader(AUTHORIZATION, "TOKEN");
CloseableHttpClient client = HttpClients.createDefault();
CloseableHttpResponse response = client.execute(httpGet);
HttpEntity entity = response.getEntity();

InputStream content = entity.getContent();
LOGGER.info("** Stream length '{}'", content.available());  // 'content.available()' throwing java.io.EOFException
```

**Exception stackTrace**

```
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
	at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
	at org.apache.http.client.entity.LazyDecompressingInputStream.available(LazyDecompressingInputStream.java:86)

```
**Maven details** -
`HttpClientMock `- 1.8.1 (I know it's year old version, if you have any sample with latest verion for ZIP file then please share)

**Comment by PawelAdamski** [comment]
Hi @abhikt48 
HttpClientMock works fine with Zip files.
IMO the problem is in your example. Please note that in line `CloseableHttpClient client = HttpClients.createDefault();` you are creating new HttpClient which doesn't uses HttpClientMock.

Here is my example which works without any exceptions:
```
    Action action = new Action() {
      @Override
      public HttpResponse getResponse(Request request) throws IOException {
        BasicHttpResponse response = new BasicHttpResponse(new ProtocolVersion("http", 1, 1), 200, "ok");
        FileEntity entity = new FileEntity(new File("C:\example.zip"));
        response.setEntity(entity);
        return response;
      }
    };

    HttpClientMock httpClientMock = new HttpClientMock();

    httpClientMock.onGet("http://xxx.com").doAction(action);

    HttpGet httpGet = new HttpGet("http://xxx.com");
    CloseableHttpResponse response = httpClientMock.execute(httpGet);
    HttpEntity entity = response.getEntity();

    InputStream content = entity.getContent();
    System.out.println(   "** Stream length "+ content.available());  // 'content.available()' throwing java.io.EOFException
```

Please let me know if that helps you.

**Comment by PawelAdamski** [comment]
Closing due to lack of response from author.
